apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nest-typescript-starter
    tier: backend
    deployedBy: deploy-node-app
  name: nest-typescript-starter
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nest-typescript-starter
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nest-typescript-starter
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: "jefftian/nestjs-hero-grpc-sample-with-health-check:0a7688d"
          imagePullPolicy: Always
          name: nest-typescript-starter
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 3m
              memory: 64Mi
          command:
            - node
            - dist/main.js
          envFrom: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
