apiVersion: v1
kind: Service
metadata:
  name: nest-typescript-starter
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: nest-typescript-starter
    tier: backend

